### ISSUE TITLE
Support OTF Screen Commands

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wedm#31]
It would be nice if we supported JLab On-The-Fly (OTF) generated EDM screens launched from a Command Widget.   We have a server-side OTF Generator cache already for screens launched from WMenu.   The OTF cached screen names will soon map to a file on the filesystem that can be obtained by base64 encoding the OTF command.   We should create a new environment variable named something like `OTF_DIR`, and if configured, attempt to convert OTF commands to related display links in the OTF_DIR.

See: https://developer.mozilla.org/en-US/docs/Web/API/btoa

Related: https://github.com/JeffersonLab/wedm/issues/27

**Comment by theojlab** [comment]
I've created and run a php script that extracted every OTFLauncher command found under in every .edl file starting at /cs/opshome/edm.  For purposes of testing, the resulting edl files have been stashed in /cs/opshome/edm/wedm/otf/tmp.

The function and corresponding regex that I used to obtain the command signatures follows.  The signatures thus produced were executed and then saved into edl files whose filename is the string obtained by base64-encoding the commands.

```php
function findOTFLauncherCommands($file) : array {
    /*
     * The pattern for OTFLauncher in an edl file is
     *   It is found on a line whose first non-whitespace character is an integer
     *   Its line may contain content between integer and the string "OTFLauncher"
     *   The command that includes OTFLauncher may or may not be quoted.
     *   The command terminates at a closing quotation, a newline, or a display-related @directive
     *
     *  Example 1 - intervening text between number and OTFLauncher, and trailing @directive :
     *
     * command {
     *  0 export DISPLAY=<DSPNAME>; /cs/prohome/bin/edmRun /cs/opshome/edm/bpm/spikes/IPM_O_SpikeKey.edl
     *  1 export DISPLAY=<DSPNAME>; OTFLauncher bpm bpmoffsum -region bsydump @<DSPNAME>+<WINID>
     * }
     *
     *  Example 2 - Only command and enclosed in quotation marks :
     *
     * command {
     *  0 "OTFLauncher viewer viewerCommander"
     * }
     *
     */
    $regex='/[\d\s]+[\"]*(OTFLauncher.*)(([\"\s]+)|(@.*)|\s+)$/';
    $cmds = [];
    if (is_readable($file)){
        foreach (file($file) as $line) {
            // Note the trim of leading and trailing whitespace
            if (preg_match($regex, trim($line), $matches)){
                $cmds[] = $matches[1];
            }
        }
    }
    return $cmds;
}
```

To see the OTF command that generated any given .edl file one need simply feed the filename less the .edl file extension to the base64 command as follows:

```sh
echo T1RGTGF1bmNoZXIgYnBtIGJwbXNwaWtlcyAtem9uZSBBUkM4ICAtZGlzcGxheSBhYnMzMCAtdGl0bGUgJ0FSQzgnIA== | base64 -d
```

**Comment by theojlab** [comment]
Some things that need to be addressed:

1.   There are a handful (less than a dozen) of instances where the OTFLauncher command in the source edl file spans multiple lines using backslash line continuation character.  The regex above can't handle that.  
2.   The output edl files themselves have embedded OTFLauncher commands.  Will need to run through them and generate the edl files for any new command signatures they may introduce that weren't generated on the first pass.
3.  The regex above is failing to exclude the @ directive (ex: @<DSPNAME>+<WINID>) in some instances.  Need to investigate that further.
4.  Quite a few of the OTFLauncher commands that were executed logged errors.  They look like errors with the commands that were found in the edl files rather than a problem with the script I'm using to call them.  Some examples:
 
<CED API>: No such Zone
<CED API>: No such element [FSD_FSDMASTER]
<CED API>: No such element [BLMNL3A]
<EDL API>: No such color name [""]

**Comment by theojlab** [comment]
I have the otf-pregen program to the point where it makes 99% of all OTFLauncher invocations found in EDL files, JMenu, and derived EDL files.  The exceptions are noted in the comments of the function above -- namely the hairier, riskier patterns that contain back-ticks, semi-colons or macro variables or that are multi-line,    I am currently working out the kinks of executing it via cron environment.  But then it's ready for service.

**Comment by slominskir** [comment]
Map of OTFLauncher command to pre-generated screen is at `edm/wedm/otf-pregen/edl.json`
