### ISSUE TITLE
EDM object TextupdateClass PV without EGU results in CAException

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/wedm#36]
This is a regression from https://github.com/JeffersonLab/wedm/issues/33.   Now, we sorta have the opposite problem.   It turns out EPICS PVs often do not have an EGU field.   The recent enhancement aggressively looks for the EGU field though, resulting in CAExceptions, which manifest on WEDM screens as white text / white backgrounds.

WEDM does not monitor complex CA Types, only primitive types.  If monitoring a [GR or CTRL](https://epics.anl.gov/base/R3-14/12-docs/CAref.html#Channel) complex type struct we could potentially just check if the units field was present client-side.  However, with the a-la-carte monitoring approach it appears we need to catch ChannelNotFoundException instead.   Else figure out a way to determine ahead of time if a PV actually has an EGU field.

**Comment by slominskir** [comment]
For background, we use the primitive type monitoring / single field monitoring exclusively for several reasons:
1. It's the simplest method as it can be used to monitor everything, just separately
1. That's what epics2web supports
1. It's the default method for JCA (Java CA lib)
1. There were bugs in JCA and/or the EPICS version at JLab in the past, and may be still, such that monitoring a complex type didn't result in updates if a non-value field changed (this is especially problematic for long running monitors, that are shared among multiple users, such as with WEDM).
1. I actually don't know how EDM determines which complex type to monitor (might be widget specific?)
1. Monitoring more fields than you use is a waste (monitoring individual fields should be re-using CA "Transport") 
1. It is clumsy to handle a monitor update on a struct of fields (not sure how that even works, might need to assume every field changed?  Otherwise must be extra field/mask that reveals what changed?)

For these reasons, plus don't want to fundamentally change how WEDM works now, using complex struct is not a good solution.    So we'll probably just catch the Exception and log it.   Maybe encourage users who use TextupdateClass widget to only use PVs with EGU to minimize wasted monitors else use a different widget as there are plenty that widgets for text.

**Comment by kasemir** [comment]
It might be too late to change this now for wedm/epics2web, but one common client pattern as used by EDM, CS-Studio, display builder web runtime, ... is this:
On connection, fetch the DBR_CTRL_xxx type to get all metadata (limits, units, precision, ...). Then subscribe to the basic type for value updates. For a while now, IOCs also support the DBE_PROPERTY event, so you may subscribe to the DBR_CTRL_xxx type with DBE_PROPERTY, only getting updates when the meta data changes, and to the basic type with DBE_VALUE|DBE_ALARM, getting updates for all value and alarm changes.

For Channel Access, the get-CTRL-then-mointor-value method or two subscriptions (DBE_PROPERTY for CTRL_.. plus other for value) are necessary to get all the information. Just one subscription for DBR_CTRL_.. would "work", but creates unnecessary network traffic because all the data is always sent. For PV Access, a plain subscription of course sends just what changes, so there only one subscription is necessary, but we don't have that for CA. 

Creating separate channels for PV.EGU, PV.PREC, PV.... has three downsides: It ends up creating  many more subscription than just the two described above; not all records have all those fields, so you'll have to start by fetching PV.RTYP to get the record type, then hard-code a list of field for each record; it's limited to IOCs with actual records. Doesn't work with PCAS-based CA servers which serve the DBR_CTRL_.. types just fine but there are no underlying records and thus no PV.xxx fields.

**Comment by slominskir** [comment]
The caget query on a DBR_CTRL first to obtain the metadata is an interesting approach.  WEDM has historically just relied on EDM attributes to tell us what to query instead of asking CA for metadata, which assumes EDM's EDL files are configured to query a PV of the correct type (needed fields exist), and this has worked pretty well until about now, several years later :).  This one widget units feature probably isn't worth redesigning everything - there are plenty of work arounds like use the different, but functionally similar text widget if don't actually want units, or just put the units in a static text label widget if you do as it probably isn't changing, or live with likely soon-to-be swallowed exception.

The epics2web app has support for caget, though we'd need to add a flag requesting DBR_CTRL instead of a simple value primitive.  Sounds like the most robust way would be camonitor of DBR_CTRL leveraging DBE_PROPERTY, though I'm not sure how well CAJ would handle that (or JLab's legacy EPICS installation for that matter).      

I think the separate field per channel only ends-up worse in some cases, while it's better in others.  In simple cases when only the value is needed it clearly wins as there is no wasted initial get/monitor on the CTRL metadata.  It's also much simpler.    I don't think it's necessary to query RTYP as EDM itself provides the metadata, except in this one case we just stumbled on.   Not working with PCAS-based servers does sound like a limitation, but this isn't something that's ever been a problem I'm aware of - I guess we don't use them at JLab and it doesn't sound like a great idea to design a server that doesn't expose the individual fields, but I'm not familiar with PCAS so there probably is a good reason.
